# Generated by Django 3.2.9 on 2022-02-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_time_login',
            field=models.BooleanField(default=True),
        ),
    ]
